### ISSUE TITLE
Loading model in keras giving error - Unknown layer: Multiplexer

### ISSUE THREAD

**Issue by 2vin** [danielegrattarola/keras-multiplexer#2]
Please let me know how to load a model trained using Multiplexer layer in Keras for inference.

**Comment by danielegrattarola** [comment]
I suggest you to have a look at the `custom_objects` flag, documented in the [Keras FAQ](https://keras.io/getting-started/faq/#handling-custom-layers-or-other-custom-objects-in-saved-models).

All the best, 
Daniele

**Comment by 2vin** [comment]
First of all, thank you for reply.
I tried the same but unfortunately it did not work. Do you have any example or something?

**Comment by danielegrattarola** [comment]
Could you provide an example of your current code?

Something like this should work:

```python
from multiplexer import Multiplexer
from keras.models import load_model

model = load_model('my_model.h5', custom_objects={'Multiplexer': Multiplexer}
```

**Comment by 2vin** [comment]
Yes, I tried exactly the same thing, here is the output-
![Selectionshot_2019-11-27_23:04:22](https://user-images.githubusercontent.com/38634222/69746452-52b4af00-116a-11ea-842e-f9c8734ed505.png)

**Comment by 2vin** [comment]
if you want to try it you can make simple model in Keras, and try to save and load it for inference. If you want a ready-made code, try [this](https://github.com/2vin/multiplexed_cnn)

**Comment by danielegrattarola** [comment]
Can you try again with the latest commit (5e5aa52783c5ebb4c459d4619299751231af38f2)?

Cheers

**Comment by 2vin** [comment]
Thanks for your efforts. Unfortunately, the above solution did not work for me. But this worked-

> 
>     def get_config(self, **kwargs):
>     	config = super().get_config()
>     	config['output_dim'] = self.output_dim
>     	config['nb_ctrl_sig']= self.nb_ctrl_sig
>     	return config
>

**Comment by danielegrattarola** [comment]
I'm sorry, I rushed to commit and copy-pasted the wrong thing. 
It's fixed now, thanks for noticing.
